name: Asset Quality Workflow

on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run npm install
      working-directory: ./util
      run: |
        npm install

    - name: Run npm check
      working-directory: ./util
      run: |
        npm run check
